  app_key: o5eqkpfbxpvtuv9
  app_secret: "eviyghs02ctt7ie"
  access_token: "zzu7cq08fxe0sb2g"
  access_token_secret: "2exjfanee8bfio1"
  user_id: "295950005"
  access_type: "app_folder"
# production:
#   app_key: "o5eqkpfbxpvtuv9"
#   app_secret: "eviyghs02ctt7ie"
#   access_token: "zzu7cq08fxe0sb2g"
#   access_token_secret: "2exjfanee8bfio1"
#   user_id: "295950005"
#   access_type: "app_folder"





# app_key = ENV["DROPBOX_APP_KEY"]     #"o5eqkpfbxpvtuv9"
# app_secret= ENV["DROPBOX_APP_SECRET"] #"eviyghs02ctt7ie"
# access_token = ENV["DROPBOX_ACCESS_TOKEN"] # "zzu7cq08fxe0sb2g"
# access_token_secret = ENV["DROPBOX_ACCESS_TOKEN_SECRET"] #"2exjfanee8bfio1"
# user_id = ENV["DROPBOX_USER_ID"] #"295950005"
# access_type= "app_folder"
